<?php

return [
    'max_terms' => 12,
    'snippet_length' => 140,

    'weights' => [
        'title_exact' => 180,
        'title_prefix' => 120,
        'title_phrase' => 90,
        'title_term' => 45,
        'summary_term' => 28,
        'tag_term' => 36,
        'category_term' => 18,
        'department_term' => 18,
        'source_name_term' => 16,
        'source_app_term' => 14,
        'fulltext_multiplier' => 24,
    ],

    'stop_words' => [
        'dan',
        'atau',
        'yang',
        'untuk',
        'dengan',
        'dari',
        'ke',
        'di',
        'the',
        'and',
        'for',
        'to',
        'of',
        'sop',
        'prosedur',
        'procedure',
    ],

    'concepts' => [
        ['cuti tahunan', 'annual leave', 'yearly leave'],
        ['pengajuan cuti', 'leave request', 'leave application', 'request leave'],
        ['cuti sakit', 'sick leave', 'medical leave', 'izin sakit'],
        ['cuti melahirkan', 'maternity leave'],
        ['cuti tanpa gaji', 'unpaid leave'],
        ['lembur', 'overtime'],
        ['absensi', 'attendance', 'kehadiran', 'presensi'],
        ['penggajian', 'payroll', 'gaji', 'salary'],
        ['klaim', 'reimbursement', 'penggantian biaya', 'expense claim'],
        ['perjalanan dinas', 'business travel', 'travel request'],
        ['pengadaan', 'procurement', 'purchasing', 'pembelian'],
        ['stok', 'persediaan', 'inventory'],
        ['pelatihan', 'training'],
        ['penilaian kinerja', 'performance review', 'performance appraisal'],
        ['keselamatan', 'k3', 'safety'],
        ['laporan insiden', 'incident report'],
        ['onboarding', 'orientasi karyawan', 'employee onboarding'],
        ['offboarding', 'pengunduran diri', 'termination', 'resignation'],
        ['persetujuan', 'approval', 'otorisasi', 'authorization'],
        ['pengembalian barang', 'return', 'refund'],
        ['kebijakan', 'policy', 'guideline'],
    ],

    'token_map' => [
        'cuti' => ['leave', 'time off'],
        'tahunan' => ['annual', 'yearly'],
        'izin' => ['permission', 'approval', 'leave'],
        'pengajuan' => ['request', 'submission', 'application'],
        'karyawan' => ['employee', 'staff'],
        'pegawai' => ['employee', 'staff'],
        'gaji' => ['salary', 'payroll'],
        'pembelian' => ['purchase', 'procurement'],
        'barang' => ['item', 'goods', 'inventory'],
        'pelatihan' => ['training'],
        'keselamatan' => ['safety'],
        'insiden' => ['incident'],
        'perjalanan' => ['travel', 'trip'],
        'dinas' => ['business', 'official'],
        'klaim' => ['claim', 'reimbursement'],
        'pengembalian' => ['return', 'refund'],
        'persetujuan' => ['approval', 'authorization'],
    ],
];
